# Generated by Django 2.0.5 on 2019-03-25 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, unique=True)),
                ('product_description', models.TextField(blank=True)),
                ('product_picture', models.ImageField(blank=True, upload_to='category')),
            ],
            options={
                'verbose_name_plural': '商品类别表',
                'db_table': '商品类别表',
            },
        ),
        migrations.CreateModel(
            name='Productlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, unique=True)),
                ('product_description', models.TextField(blank=True)),
                ('product_picture', models.ImageField(blank=True, upload_to='category')),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('shelves', models.BooleanField(default=True)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.ProductCategory')),
            ],
            options={
                'verbose_name_plural': '产品列表',
                'db_table': '产品列表',
                'ordering': ('-create_time',),
            },
        ),
    ]
