# Generated by Django 2.0.5 on 2019-03-31 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_auto_20190331_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
