# Generated by Django 2.0.5 on 2019-03-31 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_auto_20190331_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='name',
            new_name='名称',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='picture',
            new_name='图片',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='description',
            new_name='描述',
        ),
        migrations.RenameField(
            model_name='productlist',
            old_name='name',
            new_name='名称',
        ),
        migrations.RenameField(
            model_name='productlist',
            old_name='picture',
            new_name='图片',
        ),
        migrations.RenameField(
            model_name='productlist',
            old_name='description',
            new_name='描述',
        ),
    ]
