# Generated by Django 2.0.5 on 2019-03-31 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_auto_20190331_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productlist',
            options={'ordering': ('-创建时间',), 'verbose_name_plural': '产品列表'},
        ),
        migrations.RenameField(
            model_name='productlist',
            old_name='price',
            new_name='价格',
        ),
        migrations.RenameField(
            model_name='productlist',
            old_name='create_time',
            new_name='修改时间',
        ),
        migrations.RenameField(
            model_name='productlist',
            old_name='update_time',
            new_name='创建时间',
        ),
        migrations.RenameField(
            model_name='productlist',
            old_name='shelves',
            new_name='已上架',
        ),
        migrations.RenameField(
            model_name='productlist',
            old_name='stock',
            new_name='库存',
        ),
        migrations.RenameField(
            model_name='productlist',
            old_name='category',
            new_name='所属类别',
        ),
    ]
